<?xml version="1.0" encoding="utf-8"?>
<!--
     Description    xrt_flow project file.
     Copyright (C) 2022 Advanced Micro Devices, Inc. All rights reserved.
-->
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros">
    <XRT_FLOW_TEST_CASE>conv</XRT_FLOW_TEST_CASE>
  </PropertyGroup>
  <PropertyGroup />
  <ItemDefinitionGroup />
  <ItemGroup>
    <BuildMacro Include="XRT_FLOW_TEST_CASE">
      <Value>$(XRT_FLOW_TEST_CASE)</Value>
    </BuildMacro>
  </ItemGroup>
</Project>
